server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerup
    username: brito
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

appDescription: "Pragma PowerUp"
appVersion: "1.0.0"
